name: 'release'
on:
  push:
    branches:
      - release

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd ./Assets/jp.ootr.common && zip -r ../../release.zip ./* && cd ../..
      - uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            release.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}